services:
  jenkins:
    image: jenkins/jenkins:2.568.2-lts-alpine
    environment:
      JENKINS_JAVA_OPTS: -Xms${JENKINS_HEAP_MIN:-256}m -Xmx${JENKINS_HEAP_MAX:-512}m -Djava.awt.headless=true -Djenkins.install.runSetupWizard=${JENKINS_SETUP_WIZARD:-true} ${JENKINS_EXTRA_JAVA_OPTS}
      JENKINS_OPTS: ${JENKINS_PREFIX:+--prefix=${JENKINS_PREFIX}}
      JENKINS_SLAVE_AGENT_PORT: ${JENKINS_AGENT_PORT:-50000}
      TZ: ${TZ}
    volumes:
      - ${APP_DATA_DIR}/data:/var/jenkins_home
    deploy:
      resources:
        limits:
          memory: ${JENKINS_MEMORY_LIMIT:-1024}M
        reservations:
          memory: ${JENKINS_MEMORY_RESERVATION:-256}M
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
